language: c
install:
  - sudo apt-get update -yqq
  - sudo apt-get install mono-devel mono-xbuild libgtk2.0-cil-dev intltool nunit-console yelp-tools -yqq
script:
  - ./autogen.sh && make
  - make test
  - make check
