name: Build

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build Pinta.sln
    - name: Test
      run: dotnet test Pinta.sln
