name: Build

on:
  # Build on new commits or pull requests.
  push:
  pull_request:
  schedule:
    # Run every week just to make sure the CI environment still works.
    - cron: '0 0 * * 0'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # TODO - upload an artifact with the build results (see master branch)
    - name: Build
      run: dotnet build Pinta.sln
    - name: Test
      run: dotnet test Pinta.sln
